<?php
// This class is automatically generated by the system
// and is intended for testing purposes only.
namespace Admin\Controller;

use Think\Controller;

class _AuthController extends Controller
{
	public function _initialize()
	{
		// Check user permissions during initialization.
		if (empty($_SESSION["user"])) {
			header("Content-type:text/html;charset=utf-8");
			echo "<script>alert('Currently not logged in, please check');</script>";
			echo "<script>location.href='" . __MODULE__ . "/Index/login'</script>";
			exit;
		}
	}
}
?>
