<?php
// This class is automatically generated by the system
// and is intended for testing purposes only.
namespace Admin\Controller;
use Think\Controller;

// MemberController class for managing member information.
class MemberController extends _AuthController {

	// Display the index page with a list of members.
	public function index(){
		$count = M("member")->count();
		$page = new \Think\Page($count, 10);
		$pageStr = $page->show();
		$limit = $page->firstRow . ',' . $page->listRows;
		$list = M("member")->limit($limit)->select();
		$this->assign("pageStr", $pageStr);
		$this->assign("list", $list);
		$this->display();
	}

	// Display the member's bills.
	public function mem_bill($member_id){
		// All order tables and their corresponding personal information. /*有吻茶(台語)*/
		$data['member_id'] = $member_id;
		$count = D("BillView")->where($data)->count();
		$page = new \Think\Page($count, 10);
		$pagestr = $page->show();
		$limit = $page->firstRow . ',' . $page->listRows;
		$list = D("BillView")->where($data)->order("bill.datetime desc")->limit($limit)->select();
		// echo D()->getlastsql();
		$this->assign("pagestr", $pagestr);
		$this->assign("list", $list);
		$this->display();
	}

	// Display the member's balance.
	public function mem_balance($member_id){
		$data['member_id'] = $member_id;
		$count = M("mem_balance")->where($data)->count();
		$page = new \Think\Page($count, 10);
		$pageStr = $page->show();
		$this->assign("pageStr", $pageStr);
		$limit = $page->firstRow . ',' . $page->listRows;
		$list = M("mem_balance")->where($data)->limit($limit)->order("datetime desc")->select();
		$this->assign("list", $list);
		$this->display();
	}

	// Display the member's addresses.
	public function mem_address($member_id){
		$data['member_id'] = $member_id;
		$count = M("mem_address")->where($data)->count();
		$page = new \Think\Page($count, 10);
		$pageStr = $page->show();
		$this->assign("pageStr", $pageStr);
		$limit = $page->firstRow . ',' . $page->listRows;
		$list = M("mem_address")->where($data)->limit($limit)->select();
		$this->assign("list", $list);
		// echo M()->getlastsql();
		$this->display();
	}

	// Display the member's refunds.
	public function mem_refund($member_id){
		$data['member_id'] = $member_id;
		$count = M("bill_refund")->where($data)->count();
		$page = new \Think\Page($count, 10);
		$pageStr = $page->show();
		$this->assign("pageStr", $pageStr);
		$limit = $page->firstRow . ',' . $page->listRows;
		$list = M("bill_refund")->where($data)->limit($limit)->select();
		$this->assign("list", $list);
		// echo M()->getlastsql();
		$this->display();
	}

	// Delete a member.
	public function delete($id){
		M("member")->where("id=".$id)->delete();
		echo "<script>location.href='".__CONTROLLER__."/member_list'</script>";
	}

	// Display the balance information.
	public function balance(){
		if ($_POST['name'] != "") $data['name'] = array("like", '%' . $_POST['name'] . '%');

		$count = D("BalanceView")->where($data)->count();
		$page = new \Think\Page($count, 10);
		$pageStr = $page->show();
		$this->assign("pageStr", $pageStr);
		$limit = $page->firstRow . ',' . $page->listRows;
		$list = D("BalanceView")->where($data)->limit($limit)->order("datetime desc")->select();
		$this->assign("list", $list);

		$this->display();
	}
}
?>
