<?php
// This class is automatically generated by the system
// and is intended for testing purposes only.
namespace Home\Controller;
use Think\Controller;

// Base controller with authentication checks for testing purposes.
class _AuthController extends Controller {
	protected $pageSize = 10;

	// Initialization method called before any action.
	public function _initialize()
	{
		// Check if the user is authenticated.
		if ($_SESSION['account'] == null) {
			header("Content-type:text/html;charset=utf-8");
			echo "<script>alert('Illegal login user！');</script>";
			echo "<script>location.href='".__MODULE__."/Index/login'</script>";
			exit;
		}
	}
}
?>
